### ISSUE TITLE
Not working at all in IE8

### ISSUE THREAD

**Issue by tristangrace** [HubSpot/sortable#12]
When I try to use Sortable on the demo site It doesn't work at all.
This is the error.

Object doesn't support this property or method
sortable.js    Line 52
Code: 0       Char 7
URI: http://github.hubspot.com/sortable/js/sortable.js

**Comment by CodeDux** [comment]
This was fixed in 57212652c8141ea913160011cf20a9f48e1e8c44 right?

**Comment by adamschwartz** [comment]
@tristangrace @CodeDux yes I believe so. Thanks.

@timmfin et al. please close. :wink:
