### ISSUE TITLE
Issue with Google chrome (newest)

### ISSUE THREAD

**Issue by corebyte** [HubSpot/sortable#17]
I have a table with data-value="" and it does not work on alphabet. It are names and there is no logical in the sorting in ascending of descending.

This problem i don't have in Firefox or Safari.

Please help me.

**Comment by adamschwartz** [comment]
Hey @corebyte I’m having trouble reproducing this. Would you mind sharing a complete code example or [jsFiddle](http://jsfiddle.net) demo to help us reproduce the issue so we can look into it further? Thanks so much in advance. Sorry for the delay in getting back.

**Comment by adamschwartz** [comment]
Closing for now. Please let us know if this is still an issue for you and we’ll reopen. Thanks!
