### ISSUE TITLE
It doesn't work in Firefox

### ISSUE THREAD

**Issue by smartcorestudio** [HubSpot/sortable#18]
You can just check your demo in FF36.

**Comment by smartcorestudio** [comment]
It works if we comment the line
`"touchDevice = 'ontouchstart' in document.documentElement"`

**Comment by adamschwartz** [comment]
Thanks for reporting this @smartcorestudio. Sorry for the delay. I just tested in FF39 for Mac OS X and it worked. Do you think it’s possible https://github.com/HubSpot/sortable/issues/23 was the issue? (Were you on a 2-in-1 or tablet running Firefox?) Thanks in advance.

**Comment by adamschwartz** [comment]
Assuming this was #23, that was fixed with cab1613b721e7a7512417ded8fb62d163c647777. Please let us know though if your issue isn’t fixed with by cab1613b721e7a7512417ded8fb62d163c647777 and we’ll reopen. Thanks!
