### ISSUE TITLE
data-value="-1" doesn't work

### ISSUE THREAD

**Issue by Machou** [HubSpot/sortable#19]
Hello

If i put "-1" on data-value, he don't sort

why ?

**Comment by adamschwartz** [comment]
Hey @Machou, unfortunately I’m having trouble reproducing this issue. When I put `data-value="-1"` on a cell in a `numeric`-type column, I’m seeing it sort properly with that value. And indeed `'-1'.match(/^-?[£$¤]?[\d,.]+%?$/)` (the `numberRegExp` currently used to test for the column type) returns `['-1']`. Would you mind providing a complete code example or jsFiddle so we can reproduce the issue on our end? Thanks.
