### ISSUE TITLE
Sorting is not working

### ISSUE THREAD

**Issue by Erfahrungen** [HubSpot/sortable#20]
Hi there,

I really like your lightweight table sorter. But I've just realized it's not working, also in the demo on your website here: http://github.hubspot.com/sortable/

If you sort descending by "Usage" the Opera entry with 1.03% is listed before Other with 2.44%.

Can you fix that?

Thanks a lot

**Comment by kirtamus** [comment]
Hi,

Not sure if you figured it out but the td in question has the attribute data-value="0" added to it.

I think this may have been put in as an example of using the data-value attribute to change how the data is sorted.... then again it could just be human error ;)

**Comment by adamschwartz** [comment]
@kirtamus you are correct. Thanks for filling in here.

@timmfin please close this as well.

**Comment by adamschwartz** [comment]
Thanks again :)

**Comment by kirtamus** [comment]
no problem :)
