### ISSUE TITLE
Stale version link on landing page

### ISSUE THREAD

**Issue by khawkins98** [HubSpot/sortable#22]
Not a code issue, but the web landing page links to the old version (0.5.0) and mainstream is at (0.6.0). 

Doubly an issue as IE8 support is much better in 0.6

http://github.hubspot.com/sortable/

**Comment by adamschwartz** [comment]
Thanks!

@timmfin @geekjuice @TrevorBurnham I tried to `npm install -g hsdoc` and run `hsdoc -a` but ran into an issue pushing.

```
Error pushing { [Error: Command failed: ERROR: Permission to HubSpot/sortable.git denied to adamschwartz.
fatal: Could not read from remote repository.
```

Would one of y’all mind either giving me access back or running `hsdoc` yourselves? Thanks in advance.

**Comment by timmfin** [comment]
Just ran it: https://github.com/HubSpot/sortable/commit/d500d321a433cbc290a9af1915ebfe35f931893d

**Comment by adamschwartz** [comment]
Thanks @timmfin
