### ISSUE TITLE
Clicks do not work on touch devices

### ISSUE THREAD

**Issue by tuttleb** [HubSpot/sortable#23]
If you are on a device which supports both touch and mouse input (for example a Windows 8 2-in-1) then only touches will sort the table. Clicking with a mouse does nothing. This can be recreated on the demo page if you have a touch enabled device.

Another way to recreate this is to hard code this line:

    touchDevice = 'ontouchstart' of document.documentElement
to always be true and then click on a `th` to attempt to sort.

**Comment by grotos** [comment]
Same here: it works in Firefox, but in Chrome you have to touch <th> to sort table.

**Comment by adamschwartz** [comment]
Ahh, it makes sense that would be the behavior based on [this](https://github.com/HubSpot/sortable/blob/f9303b430409c545d7bb98b7d1b347272de15e4a/coffee/sortable.coffee#L7) and [this](https://github.com/HubSpot/sortable/blob/f9303b430409c545d7bb98b7d1b347272de15e4a/coffee/sortable.coffee#L39).

If we bind to both `touchstart` and `click`, maybe we could do something like [this](http://stackoverflow.com/a/11507558/131898)? @zackbloom know of a better pattern here?

**Comment by zackbloom** [comment]
What you really want is Pointer Events (https://github.com/jquery/PEP), but as browser support is not great yet, a common thing is to bind to both `touchstart` and `click`, but either debounce (like the first example in that SO post), or mark the event as handled somehow (like the second).  I think what you suggest would do exactly what you need.

**Comment by adamschwartz** [comment]
whoa cool, thanks. [microsoft is killin it](http://caniuse.com/#feat=pointer) right now :P

cool, yeah. is that kosher though marking the event itself?

**Comment by zackbloom** [comment]
Depends who you ask.  I would double check that it doesn't error in old-IE or Safari, but my guess is that you'll get away with it.

**Comment by adamschwartz** [comment]
hehe k, thx

**Comment by adamschwartz** [comment]
Fixed with cab1613b721e7a7512417ded8fb62d163c647777

**Comment by smartcorestudio** [comment]
Hmm... Yust tested your demo in the latest Firefox on classic old-school desktop (without touch support) on Windows 10. Here is the screencast: https://www.youtube.com/watch?v=E33lwZd8dio

**Comment by adamschwartz** [comment]
@smartcorestudio thanks so much for sharing that. [v0.8.0](https://github.com/HubSpot/sortable/releases/tag/v0.8.0) should fix it. Please let me know. Thanks!

**Comment by smartcorestudio** [comment]
It works OK now! Thank you for quick fix!

**Comment by adamschwartz** [comment]
@smartcorestudio awesome. No problem! Thanks for the video. :+1:
