### ISSUE TITLE
Sort handler triggered twice on mobile

### ISSUE THREAD

**Issue by BenoitDeVrieze** [HubSpot/sortable#32]
When tapping on the header of a sortable column on a mobile device (Android, Chrome, latest) the sort handler is triggered twice resulting in the same sorting direction. On slow devices it is visible that the sorting happens twice. This makes that the user is not able to switch the sorting direction. The issue is most probably caused by differences in touch input api's of different browsers.

**Comment by zackbloom** [comment]
I can imagine this happening if the `touchstart` and `click` events are considered seperate, causing this code not work: https://github.com/HubSpot/sortable/blob/master/coffee/sortable.coffee#L41-L44
